sonar.projectKey=ribasal1_api-code-sample
sonar.organization=ribasal1


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=api-code-sample
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding

sonar.exclusions=**/__pycache__/**,**/.venv/**,**/venv/**,**/.pytest_cache/**
sonar.python.version=3.14.4
